name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: cd functions && npm ci
      # - run: cd old/first-5 && npm ci && npm run build\
      #   env:
      #     REACT_APP_GRAPHCSM_URL: ${{ secrets.REACT_APP_GRAPHCSM_URL }}
      #     REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
      #     REACT_APP_AUTHDOMAIN: ${{ secrets.REACT_APP_AUTHDOMAIN }}
      #     REACT_APP_PROJECTID: ${{ secrets.REACT_APP_PROJECTID }}
      #     REACT_APP_STORAGEBUCKET: ${{ secrets.REACT_APP_STORAGEBUCKET }}
      #     REACT_APP_MESSAGINGSENDERID: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
      #     REACT_APP_MEASUREMENTID: ${{ secrets.REACT_APP_MEASUREMENTID }}
      #     REACT_APP_APPID: ${{ secrets.REACT_APP_APPID }}
      - run: cp -r old/school old/first-5/app/build
      - uses: jonahsnider/firebase-action@1.0.7
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          args: deploy
      - name: Curl the update webhook.
        uses: wei/curl@master
        with:
          args: www.bobby-christopher.com/updateResume
